### ISSUE TITLE
New session on close/reopen browser?

### ISSUE THREAD

**Issue by klaaktu** [cbeuw/Cloak#113]
Latest build from master. ck-client + Shadowsocks creates a new session every time I close then reopen my browser, closing/creating new tabs seems fine.
( 2.1.3 doesn't seem to do this.) Is it an expected behavior of the new version?

**Comment by cbeuw** [comment]
This is most likely a regression. Unfortunately I won't have time to investigate this until two weeks later due to exams. But I will get around to it

**Comment by klaaktu** [comment]
Build from latest master looks good, thx!
