### ISSUE TITLE
UDP OpenVPN doesn't work in 2.2.0

### ISSUE THREAD

**Issue by klaaktu** [cbeuw/Cloak#117]
Unable to connect after upgrading to 2.2.0. Cloak can establish session but OpenVPN can't connect, it connected once but still couldn't open any website.

**Comment by klaaktu** [comment]
TCP also seems to be slower but it could be gfw...
And switching between "disable" and "global" in Shadowsocks on one PC disconnect the Steam client on another PC for some reason.

**Comment by klaaktu** [comment]
5cbc248 seems to be faster than 2.2.0. YT went from 2Mb to 20Mb after switching ck-client back to 5cbc248.

**Comment by klaaktu** [comment]
UDP works with 5cbc248 ck-server + 2.2.0 ck-client. Switching ck-server from 2.2.0 to 5cbc248 made YT speed go from 20Mb (max, usually under 1000kb because of gfw throttling) to 30Mb (haven't tested whether it will get throttled but it was stable in the past).

**Comment by cbeuw** [comment]
Should be fixed in https://github.com/cbeuw/Cloak/commit/ff10cbf67b8a62cf8d7b4401989f1e91745642e4. It'd be great if you can test this. If it works fine I'll do a fix release

**Comment by klaaktu** [comment]
@cbeuw ty!
Using ck-client & ck-server built from master, OpenVPN in UDP mode can connect, tho I can't test the speed, gfw seems to be good at detecting VPN. It goes from 15Mb to 1000kb in a few seconds and the IP stays throttled even if I switch to Shadowsocks.
Shadowsocks + Cloak works very well (tested using another IP, same server), 30+Mb max as before.

**Comment by cbeuw** [comment]
@klaaktu Is GFW able to detect OpenVPN when Cloak is used in non-plaintext mode?

**Comment by klaaktu** [comment]
@cbeuw idk, it seems so but maybe it's something else...
EncryptionMethod for OpenVPN is set to aes-gcm, while OpenVPN is configured to be plain-text.
For Shadowsocks, Cloak is plain and SS is aes-128-gcm.
I ran OpenVPN using the second IP, now it also stays at 1000k.
Tho there is usually no packet loss (in video games), unless I use it for a very long time.

**Comment by klaaktu** [comment]
I tested OpenVPN + Cloak again today. Both TCP and UDP mode have 20Mb+ speed on YT.
