### ISSUE TITLE
Azure Pipelines Continuous Build

### ISSUE THREAD

**Issue by notsure2** [cbeuw/Cloak#130]
Hello
@cbeuw How about setting up free Azure Pipelines Pipeline to build and push git releases from every commit ? this way you don't have to build it by hand and it doesn't remain out of date for long time until you manually release.

They give 1800 build minutes free which is enough I think for Cloak and its rate of commits.

**Comment by cbeuw** [comment]
Good shout. I didn't actually know about this. I'll set it up if it appears suitable

**Comment by notsure2** [comment]
I noticed you added the pipeline file then removed it. Not suitable ? @cbeuw

**Comment by cbeuw** [comment]
I just need to figure out how to write the yaml file properly. Currently it's complaining that it can't find GOROOT, and I don't quite know where to put the built binaries. I'll make a new branch to test the yaml so it doesn't bloat up master. I'll probably do these tomorrow because it's quite late now

**Comment by notsure2** [comment]
i think you can add a "step" that saves them in azure build artifacts. they store up to 2 GB for free. Then when you reach the limit you can delete old ones automatically I guess. Maybe there's a setting there for that. Alternatively maybe there's a step to communicate to github to publish a release. I only used the building part and use ssh to deploy for my stuff.

**Comment by cbeuw** [comment]
Ideally I want it to release to github automatically, as uploading the build artifacts manually is basically what I'm doing right now. I had a look and there is a task that lets you do that, so it's definitely achievable

**Comment by cbeuw** [comment]
It appears to be working now. Thanks again for the heads-up. I'll try to set it up for Cloak-android as well which could save a lot of work, but it's going to be more complicated I assume
