### ISSUE TITLE
X86

### ISSUE THREAD

**Issue by mehdi198080** [cbeuw/Cloak#135]
I have installed on X86 openwrt image and upload cloak file in /usr/bin but I got error.

**Comment by mehdi198080** [comment]
-ash: ck-client-linux-amd64-v2.3.0: not found

**Comment by cbeuw** [comment]
Does it work if you run /usr/bin/ck-client-linux-amd64-v2.3.0? Also is your CPU 32 or 64bit? In the former case you need the i386 version

**Comment by mehdi198080** [comment]
my cpu is 64bit 
with i386 got this error
/usr/bin/ck-client-linux-386-v2.3.0: line 1:ELFpE: not found
/usr/bin/ck-client-linux-386-v2.3.0: line 2: syntax error: unexpected "("

**Comment by cbeuw** [comment]
What about running /usr/bin/ck-client-linux-amd64-v2.3.0?

**Comment by mehdi198080** [comment]
not running

**Comment by cbeuw** [comment]
What's the error output?

**Comment by mehdi198080** [comment]
-ash: /usr/bin/ck-client-linux-amd64-v2.3.0: not found

**Comment by cbeuw** [comment]
What's the output of running `file /usr/bin/ck-client-linux-amd64-v2.3.0`? Can you see ck-client's binary if you run `ls` in `/usr/bin`?

**Comment by mehdi198080** [comment]
root@OpenWrt:/usr/bin# ls
[                             free                          obfs-local                    tee
[[                            fwtool                        obfs-server                   test
awk                           getrandom                     pgrep                         time
basename                      head                          printf                        top
bunzip2                       hexdump                       readlink                      tr
bzcat                         id                            reset                         uniq
ck-client-linux-amd64-v2.3.0  jshn                          resolveip                     uptime
clear                         jsonfilter                    scp                           usign
cmp                           killall                       seq                           v2ray-plugin_linux_amd64
crontab                       ldd                           sha256sum                     wc
cut                           less                          signify                       wg
dbclient                      logger                        sort                          wget
dirname                       lua                           ss-local                      which
dropbearkey                   luci-bwc                      ss-redir                      wireguard_watchdog
du                            md5sum                        ss-rules                      xargs
env                           mkfifo                        ss-tunnel                     yes
expr                          nano                          ssh
find                          nc                            strings
flock                         nslookup                      tail

**Comment by mehdi198080** [comment]
v2ray plugin working 

but cloak not

**Comment by cbeuw** [comment]
I'm not familiar with OpenWRT at all but I think it's because of this https://openwrt.org/faq/command_not_found, (i.e. the binary is linking to some library not present on your OS).

But this is weird because go binaries should be static. I'll look into this

**Comment by mehdi198080** [comment]
is it any chance to release new version to fix ?

**Comment by cbeuw** [comment]
https://github.com/cbeuw/Cloak/releases/tag/v2.3.1 should work, give it a try

**Comment by mehdi198080** [comment]
working perfect ,appreciate
