### ISSUE TITLE
ck-server: command not found

### ISSUE THREAD

**Issue by SpaceBurn** [cbeuw/Cloak#136]
Im trying to setup the Cloak server on Ubuntu Server 20.04 LTS but when I run ck-server -k I get the error "ck-server: command not found", what do I do?

**Comment by cbeuw** [comment]
If ck-server is in your current directory, you need to use `./ck-server` to run it, I.e. `./ck-server -k`

**Comment by SpaceBurn** [comment]
Ok thanks for the help! (this fixed my issue)
