### ISSUE TITLE
将Shadowsocks Rust的加密设置为None是否安全？

### ISSUE THREAD

**Issue by windstander** [cbeuw/Cloak#144]
因为SS的数据外层套了一个Cloak伪造的TLS，所以SS流量本身的加密设置为None是否也是安全的并能大幅提升速度？

**Comment by windstander** [comment]
Cloak isn't intended to provide transport security. The point of encryption is to hide fingerprints of proxy protocols and render the payload statistically random-like. You may only leave it as plain if you are certain that your underlying proxy tool already provides BOTH encryption and authentication (via AEAD or similar techniques).

这样来看，还是SS加密，Cloak为Plain比较好。

**Comment by MXzander** [comment]
> 因为SS的数据外层套了一个Cloak伪造的TLS，所以SS流量本身的加密设置为None是否也是安全的并能大幅提升速度？
