### ISSUE TITLE
Singleplex UDP doesn't ever close any opened sessions

### ISSUE THREAD

**Issue by notsure2** [cbeuw/Cloak#147]
i see sessions being correctly opened on every new connection tuple, however they are never getting closed even after StreamTimeout passed. In case of UDP streams need to timeout if no data is sent or received within StreamTimeout. (Only UDP).

@cbeuw 

I will see if I can make a pull request on this.

**Comment by notsure2** [comment]
Note: It's not not enough to set a read timeout or write timeout from one side. Any activity in send or receive needs to reset the timer.

**Comment by cbeuw** [comment]
I was aware of this. I'm thinking of adding a new config option specific to UDP because StreamTimeout is currently being used to close the incoming connection on the client side if they don't send anything. The UDP timeout is something quite different

**Comment by notsure2** [comment]
I think it's fine to reuse the StreamTimeout meaning for UDP mode since Cloak doesn't do both TCP and UDP at the same time. Actually, I think this might be easier to implement than I thought, I'll take a crack at it.

**Comment by cbeuw** [comment]
Thanks! BTW this affects not only Singleplex. With Multiplex it doesn't ever close any stream either. The solution should be the same and singleplex shouldn't need special treatment
