### ISSUE TITLE
"a connection has dropped unexpectedly" when closing web pages

### ISSUE THREAD

**Issue by klaaktu** [cbeuw/Cloak#156]
I get a lot of "a connection has dropped unexpectedly" message in ck-server. I think they correspond to when I close a web page in browser. Is this normal? It seems that most of the sessions were closed this way.
Client: Ubuntu 20.10 + Shadowsocks-Rust v1.9.1 + Cloak v2.5.2 (`"NumConn": 0`) + Firefox
Server: Ubuntu 20.10 + Shadowsocks-Rust v1.9.1 + Cloak v2.5.2

**Comment by malikshi** [comment]
>NumConn is the amount of underlying TCP connections you want to use. The default of 4 should be appropriate for most people. Setting it too high will hinder the performance. Setting it to 0 will disable connection multiplexing and each TCP connection will spawn a separate short-lived session that will be closed after it is terminated. This makes it behave like GoQuiet. This maybe useful for people with unstable connections

I think it's normal. I am usually numconn set 32/64 on shadow socks and numconn 1 proxying vpn

**Comment by klaaktu** [comment]
A side note: after switching to the current setup, I feel like often websites wait for some time before they start loading in. I think it was not the case before but I'm not sure. I also tested client: Win+Shadowsocks-Win+Cloak+Chrome and it's the same (maybe server related).
