### ISSUE TITLE
Build failes with "use of internal package not allowed"

### ISSUE THREAD

**Issue by Alireza2n** [cbeuw/Cloak#16]
Hi,
I am trying to build Cloak using latest source available, but no matter what I do build fails with either of these two messages:
`use of internal package not allowed`
or 
`cannot find package "github.com/cbeuw/Cloak/internal/ecdh" in any of ...`

Any suggestions?

**Comment by cbeuw** [comment]
1. Make sure you have set $GOPATH https://golang.org/doc/install#tarball

2. Did you use go get or git clone when you fetched this repo? If it's the latter please use go get instead

**Comment by Alireza2n** [comment]
Hi, 
Thanks for quick update.

> 1. Make sure you have set $GOPATH https://golang.org/doc/install#tarball
GOPATH is already set.
> 2. Did you use go get or git clone when you fetched this repo? If it's the latter please use go get instead
Using go get:
`go get github.com/cbeuw/Cloak`
And output is:
`package github.com/cbeuw/Cloak: no Go files in /root/go/src/github.com/cbeuw/Cloak`

**Comment by cbeuw** [comment]
Did you build with Makefile?

When do you get the first error message and when do you get the second one?

cd into $GOPATH/src/github.com/cbeuw/Cloak/internal/ecdh, is there anything in this folder?

**Comment by Alireza2n** [comment]
> Did you build with Makefile?

Yes, I have used make file.
 
> When do you get the first error message and when do you get the second one?

I have simply used `make server` and when failed I tried ` go get github.com/cbeuw/Cloak `.

> cd into $GOPATH/src/github.com/cbeuw/Cloak/internal/ecdh, is there anything in this folder?

Yep:
`ls  $GOPATH/src/github.com/cbeuw/Cloak/internal/ecdh`
`curve25519.go`


Here is what I've done:
1- `cd $GOPATH/src/github.com/cbeuw`
2- `git clone https://github.com/cbeuw/Cloak.git`
3- `make server`
 And output was:
```
mkdir -p build
go build -ldflags "-X main.version=master(cffee14)" ./cmd/ck-server
/usr/lib/go-1.10/src/github.com/cbeuw/Cloak/internal/server/usermanager/userpanel.go:13:2: cannot find package "github.com/boltdb/bolt" in any of:
	/usr/lib/go-1.10/src/vendor/github.com/boltdb/bolt (vendor tree)
	/usr/lib/go/src/vendor/github.com/boltdb/bolt
	/usr/lib/go-1.10/src/github.com/boltdb/bolt (from $GOROOT)
	/usr/lib/go/src/github.com/boltdb/bolt (from $GOPATH)
/usr/lib/go-1.10/src/github.com/cbeuw/Cloak/internal/multiplex/qos.go:6:2: cannot find package "github.com/juju/ratelimit" in any of:
	/usr/lib/go-1.10/src/vendor/github.com/juju/ratelimit (vendor tree)
	/usr/lib/go/src/vendor/github.com/juju/ratelimit
	/usr/lib/go-1.10/src/github.com/juju/ratelimit (from $GOROOT)
	/usr/lib/go/src/github.com/juju/ratelimit (from $GOPATH)
/usr/lib/go-1.10/src/github.com/cbeuw/Cloak/internal/ecdh/curve25519.go:35:2: cannot find package "golang.org/x/crypto/curve25519" in any of:
	/usr/lib/go-1.10/src/vendor/golang.org/x/crypto/curve25519 (vendor tree)
	/usr/lib/go/src/vendor/golang.org/x/crypto/curve25519
	/usr/lib/go-1.10/src/golang.org/x/crypto/curve25519 (from $GOROOT)
	/usr/lib/go/src/golang.org/x/crypto/curve25519 (from $GOPATH)
make: *** [Makefile:16: server] Error 1

```

**Comment by cbeuw** [comment]
Ah I see, it's simply due to the dependencies not present. You need to do `go get github.com/boltdb/bolt`, `go get github.com/juju/ratelimit` and `go get golang.org/x/crypto/curve25519` to fetch them.

**Comment by cbeuw** [comment]
I have updated README to make clear the need of dependencies
