### ISSUE TITLE
Appropriate "ServerName" "AlternativeNames" and "RedirAddr"?

### ISSUE THREAD

**Issue by klaaktu** [cbeuw/Cloak#160]
Is `www.bing.com` hosted on `cloudflare.com`? I only get 2 IPs for it, both owned by Microsoft.

It seems hard to find "ServerName" and "RedirAddr" pairs that:
1. Are not throttled: most non-CN websites load... but slowly (or are only fast for the first few times?).
2. Have 2 or more active "DNS Name" (for "AlternativeNames" to work): `204.79.197.200` has many, but it seems most are either old or blocked or redirects to `cn.bing.com`; `microsoft.com` in IPv6 uses one IP per subdomain.
3. Serve large files (images): so as to not be suspicious to receive a large traffic from one IP.
4. Are outside China: `204.79.197.200` has a `DNS Name` for serving map tiles, but even with encrypted DNS, map images for the world are served with CN backbones in China.
5. Are hosted on the same IP range as the VPS: (probably not possible...)

**Comment by malikshi** [comment]
I need a proper example config for the client-side new feature `AlternativeNames`

**Comment by cbeuw** [comment]
@malikshi I've added an example to README

**Comment by cbeuw** [comment]
@klaaktu I don't think bing uses Cloudflare. Cloudflare services are not on `cloudflare.com` anyway.

Unless a particular ServerName causes your Cloak connection to be actively throttled, or that domain has already been flat-out blocked, I wouldn't worry too much about it. So far I haven't seen any blockages related directly to bad ServerName settings so any speculation on what works and what doesn't are just pure guesswork.

**Comment by klaaktu** [comment]
Got it, thanks
