### ISSUE TITLE
AlternativeNames shuffle connection

### ISSUE THREAD

**Issue by malikshi** [cbeuw/Cloak#163]
hi, I want to ask regarding this new feature about AlternativeNames, is it need to set `NumConn 0` to fully use AlternativeNames? when I am set `NumConn 4` or `8` it's will be like this forever, except for restarting shadowsocks-windows client that mean new connection right
>time="2021-04-19T20:56:50+07:00" level=info msg="Listening on TCP 127.0.0.1:33498 for shadowsocks client"
time="2021-04-19T20:56:56+07:00" level=info msg="Attempting to start a new session"
time="2021-04-19T20:56:56+07:00" level=info msg="Session 2797897470 established"

**Comment by notsure2** [comment]
Yes, it's best to use NumConn=0 with it. Otherwise only when the connections are ended and new ones are spawned the sni used will change.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by malikshi** [comment]
UID=uuuuu;PublicKey=kkkkkkk;ServerName=bing.com;AlternativeNames=cloudflare.com,google.com;BrowserSig=chrome;NumConn=0;StreamTimeout=300;ProxyMethod=shadowsocks;EncryptionMethod=plain;Transport=direct
>ServerName=bing.com;AlternativeNames=cloudflare.com,google.com;

Is it the right setting? but Shadowsocks windows not allowing its because of too much text in plugin options.

**Comment by notsure2** [comment]
Then shadowsocks-windows needs a pull request. You can use cloak with a config file or launch cloak by using a cmd and put the cmd file in the plugin section in shadowsocks-windows.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by malikshi** [comment]
![image](https://user-images.githubusercontent.com/9080737/115254466-93dea200-a157-11eb-9175-8bb9d9c26871.png)
thanks @notsure2  it's work and good to go
