### ISSUE TITLE
add support openwrt

### ISSUE THREAD

**Issue by malikshi** [cbeuw/Cloak#17]
this my 
>opkg print-architecture | awk '{print $2}'
all
noarch
mipsel_24kc

**Comment by beanslel** [comment]
A MIPSEL binary (mipsle) is already available, did you try it? Manually place it in /usr/bin and should be good to go.

**Comment by malikshi** [comment]
It's not working. Plugin closed evertime I'm try it.

**Comment by malikshi** [comment]
Thu Mar 14 06:01:16 2019 daemon.info ss-redir[2010]: initializing ciphers... chacha20-ietf-poly1305
Thu Mar 14 06:01:16 2019 daemon.info ss-redir[2010]: listening at 0.0.0.0:1234
Thu Mar 14 06:01:16 2019 daemon.info ss-redir[2010]: tcp port reuse enabled
Thu Mar 14 06:01:16 2019 daemon.info ss-redir[2010]: UDP relay enabled
Thu Mar 14 06:01:16 2019 daemon.info ss-redir[2010]: udp port reuse enabled
Thu Mar 14 06:01:16 2019 daemon.info ss-redir[2010]: running from root user
Thu Mar 14 06:01:16 2019 daemon.err ss-redir[2010]: plugin service exit unexpectedly

**Comment by malikshi** [comment]
@cbeuw https://github.com/shadowsocks/v2ray-plugin/pull/27 https://github.com/golang/go/issues/18162
https://github.com/golang/go/issues/18880
it should help

**Comment by cbeuw** [comment]
Thanks for pointing this out. Please try the binary I just uploaded ck-client-linux-mipsle_softfloat-1.0.0

**Comment by malikshi** [comment]
@cbeuwI will try it, sir :) I has several shadowsocks with cloak.

**Comment by malikshi** [comment]
>{
>    "server": "your ip vps",
>    "server_port": 80,
>    "password": "pass",
>    "method": "chacha20-ietf-poly1305",
>    "local_address": "0.0.0.0",
>    "plugin": "ck-client",
>    "plugin_opts": "UID=xxxxx;PublicKey=xxxxxx;ServerName=www.line.me;TicketTimeHint=3600;NumConn=100;MaskBrowser=chrome;loglevel=none",
>    "timeout": 60,
>    "reuse_port": true
>}

it is work perfectly thanks @cbeuw . it doesn't connect when I'm using config.json I think it must have loglevel=none to work
