### ISSUE TITLE
Does Cloak have IOS Support.

### ISSUE THREAD

**Issue by DiamondCodingYT** [cbeuw/Cloak#170]
The Title says it. Is there a cloak app for ios or any other way of using it on ios?

**Comment by notsure2** [comment]
Making any app for ios requires paying apple developer license and making an ios app. There is Shadowrocket app (paid) but you have to bother its developer to make sure to keep up with Cloak updates (master branch).

**Comment by DiamondCodingYT** [comment]
So can I setup cloak to use the shadowrocket plugin and then setup the shadowrock app to use the cloak plugin? Seems ok to me. Can I still use cloak to proxy stuff to openvpn, probably right? That would be a solution for me. Thanks for the help!

**Comment by notsure2** [comment]
Shadowrocket is a shadowsocks + cloak in a single app.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DiamondCodingYT** [comment]
Ah ok. So I don't need to use the shadowsocks plugin? I'll try that tomorrow.

**Comment by malikshi** [comment]
> Ah ok. So I don't need to use the shadowsocks plugin? I'll try that tomorrow.

one app with plugins(kcptun, cloak, gost, v2ray plugins) in-app, you don't need to install an additional plugins.

**Comment by DiamondCodingYT** [comment]
Ok. So I can get the Shadowrocket app to connect to my cloak-server. Sadly when I try to then connect the OpenVPN Vpn IOS switches the VPN to OpenVPN an shadowrocket gets disconnected. Is there a way to use them simultaneously?

**Comment by malikshi** [comment]
> Ok. So I can get the Shadowrocket app to connect to my cloak-server. Sadly when I try to then connect the OpenVPN Vpn IOS switches the VPN to OpenVPN an shadowrocket gets disconnected. Is there a way to use them simultaneously?

I don't think iOS allowing proxy/socks only it's must be VPN. You can't running 2 VPN at same time. So much hassle? Go buy android it's much flexible

**Comment by DiamondCodingYT** [comment]
Thanks for all your help. I'm facing a new problem with HTTP Proxies, but I have opened a new issue for this problem. So I'm closing this issue with this comment.
