### ISSUE TITLE
How to clone the server settings and db to another server?

### ISSUE THREAD

**Issue by resuls** [cbeuw/Cloak#179]
Recently I had to change my server but copying all the files under `/etc/cloak/` doesn't seem to work. I keep getting an authentication error. How can I fix it?

**Comment by cbeuw** [comment]
You should only need to move the JSON config and userinfo db. Is the path to the db inside the JSON config correct on your new server?

**Comment by resuls** [comment]
Yes, it was, I moved the whole `/etc/cloak/` which had the JSON files and the DB as well but for some reason, it keeps failing on authentication.
