### ISSUE TITLE
Can't run ck-server -k

### ISSUE THREAD

**Issue by Luka-ACCT** [cbeuw/Cloak#18]
Hi,
I downloaded the file, and tried in step 2: run ck-server -k, however it seems this can't be executed, even though I chmod already. The alert message is:
flag provided but not defined: -k
Usage of ck-server:
  -a	Admin mode
  -c string
    	pluginOpts: path to ckclient.json or options seperated with semicolons (default "ckclient.json")
  -h	Print this message
  -l string
    	localPort: same as server_port in ss config, the plugin listens to SS using this
  -p string
    	remotePort: proxy port, should be 443 (default "443")
  -s string
    	remoteHost: IP of your proxy server
  -v	Print the version number

What can I do?
Thank you.

**Comment by cbeuw** [comment]
It appears that the binary you downloaded is actually ck-client
