### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Saliizan** [cbeuw/Cloak#181]
I encountered this error while installing on Ubuntu server, please help.

```
# gitlab.com/yawning/utls.git/cpu
../go/pkg/mod/gitlab.com/yawning/utls.git@v0.0.12-1/cpu/cpu_x86.s:7:10: fatal error: textflag.h: No such file or directory
    7 | #include "textflag.h"
      |          ^~~~~~~~~~~~
compilation terminated.
# github.com/cbeuw/Cloak/internal/multiplex
internal/multiplex/stream.go:74:13: error: reference to undefined identifier ‘errors.Is’
   74 |   if errors.Is(err, errRepeatStreamClosing) {
      |             ^
note: module requires Go 1.14
```

**Comment by gokaybiz** [comment]
https://github.com/hashicorp/packer/issues/9222

**Comment by cbeuw** [comment]
As the error message said, you need go 1.14+ to compile Cloak. What's the output of `go version` for you?

**Comment by Saliizan** [comment]
go version go1.12.2 gccgo (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0 linux/amd64

**Comment by Saliizan** [comment]
> As the error message said, you need go 1.14+ to compile Cloak. What's the output of `go version` for you?

go version go1.12.2 gccgo (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0 linux/amd64
