### ISSUE TITLE
Is Wireguard supported?

### ISSUE THREAD

**Issue by ktheticdev** [cbeuw/Cloak#187]
I would like to obfuscate WireGuard traffic. Is there a way to do so?

**Comment by HirbodBehnam** [comment]
Yes it is possible. Cloak supports UDP traffic. The only thing which is hard to do is to create the `AllowedIp` list of wireguard client config which can be done with [this script](https://www.reddit.com/r/WireGuard/comments/gyb955/comment/ftcw42a/).
The rest is somewhat similar to OpenVPN.

**Comment by b1ek** [comment]
> The only thing which is hard to do is to create the `AllowedIp` list of wireguard client config which can be done with [this script](https://www.reddit.com/r/WireGuard/comments/gyb955/comment/ftcw42a/).

there is also a [web tool for that](https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/)
