### ISSUE TITLE
Cloak panel error

### ISSUE THREAD

**Issue by Ayas77** [cbeuw/Cloak#197]
Greetings, the centos 7 system, according to the instructions, I add a new client 1 time, the following times it gives an error. Here are the error logs. Help please

1. Shadowsocks- Rust installed
2. Cloak plugin installed

https://gist.github.com/L11R/a6f7a636b0e931bb155da771c301f34a

**Comment by cbeuw** [comment]
Looks like it didn't like the value you put in for SessionsCap. What did you put in the panel? I should've done more validation on this actually

**Comment by Ayas77** [comment]
> Looks like it didn't like the value you put in for SessionsCap. What did you put in the panel? I should've done more validation on this actually

I left the session cap field empty

**Comment by cbeuw** [comment]
Ah I don't think it sets a default value if it's empty. If you don't want to limit it just fill in a very big value for now. I'll give it a sensible default in a future version

**Comment by Ayas77** [comment]
> Ah I don't think it sets a default value if it's empty. If you don't want to limit it just fill in a very big value for now. I'll give it a sensible default in a future version


I've got an error again, I set SessionCap, but left other columns empty.
![2022-08-03_23-58-25](https://user-images.githubusercontent.com/109437099/182687899-d0a4a40a-1fb4-42e9-b5c9-c68e6dafe925.png)

**Comment by cbeuw** [comment]
The control panel (and the underlying API frankly) are pretty bare. If you want to have a bunch of UIDs without usage restrictions, I recommend you to just place them under `BypassUID` field as a list. But if you do want to use the control panel, for now you have to fill in every field.

**Comment by Ayas77** [comment]
> The control panel (and the underlying API frankly) are pretty bare. If you want to have a bunch of UIDs without usage restrictions, I recommend you to just place them under `BypassUID` field as a list. But if you do want to use the control panel, for now you have to fill in every field.

Thank you. The issue has been resolved so far, we will use manual mode and wait for updates
