### ISSUE TITLE
request to bind tcp

### ISSUE THREAD

**Issue by malikshi** [cbeuw/Cloak#22]
netstat -ntlp
> tcp6       0      0 :::53794                :::*                    LISTEN      4117/ck-server

request to bind tcp not tcp6

**Comment by cbeuw** [comment]
Did you use IPv6 addresses in the config files? If so, try to change them to their IPv4 equivalence (e.g. 0.0.0.0 and 127.0.0.1)

**Comment by malikshi** [comment]
> Did you use IPv6 addresses in the config files? If so, try to change them to their IPv4 equivalence (e.g. 0.0.0.0 and 127.0.0.1)


my config like this
>{
>    "server":"0.0.0.0",
>    "server_port":53794,
>    "password":"GLOBALSSH",
>    "timeout":600,
>    "method":"aes-256-cfb",
>	"fast_open":false,
>	"nameserver":"8.8.8.8",
>	"reuse_port":true,
>	"no_delay":true,
>	"mode":"tcp_and_udp",
>    "plugin":"ck-server", >"plugin_opts":"WebServerAddr=${ckwebaddr};PrivateKey=${privat};AdminUID=${admuid};DatabasePath=${ckdbp}/userinfo.db;BackupDirPath=${ckdbp};loglevel=none"
>}
after running it ck-server would bind tcp6, i like to use tcp.

**Comment by asunbb** [comment]
@malikshi Please check https://groups.google.com/forum/#!topic/golang-nuts/F5HE7Eqb6iM, maybe it will resolve you problem. Generally, if you don't enable net.ipv6.bindv6only(default is 0) manually, your server could receive ipv4 packets from ipv6 sockets via ipv4-mapped ipv6 address.
