### ISSUE TITLE
Question about EncryptionMethod for wireguard traffic

### ISSUE THREAD

**Issue by bingzhangdai** [cbeuw/Cloak#220]
I have already successfully run wireguard with cloak. From the wiki, 
```
You must not leave EncryptionMethod as plain in Cloak client's configuration file because OpenVPN gives out fingerprint. Change it to aes-gcm or chacha20-poly1305
```

I am wondering if it also holds true for wireguard. Now I leave the EncryptionMethod as plain.

**Comment by valerius2k** [comment]
The intention of EncryptionMethod is to hide fingerprints of an underlying proxy. WG should have its own fingerprint too. So if you set EncryptionMethod to plain, the fingerprint will be exposed and your ISP could detect and block it. The data stream has no definite fingerprint only if its data looks like a white noise. But AFAIK it's not so with WG. WG is very good detectable and is blocked more often than other VPN protocols.

**Comment by bingzhangdai** [comment]
@valerius2k Thanks for your clarification. It is truly clear!
