### ISSUE TITLE
File naming differences?

### ISSUE THREAD

**Issue by eleius** [cbeuw/Cloak#237]
Thanks for the new pre-release. I was wondering what is the difference between the 2.7.1 and v2.7.1 releases (e.g. ck-server-linux-amd64-2.7.1-pre and ck-server-linux-amd64-v2.7.1-pre) as the file sizes also differ.

**Comment by cbeuw** [comment]
Looks like my CI script did run after manual tagging. I've removed the duplicates. The files should have identical functionalities, the difference in size is likely due to different Go versions
