### ISSUE TITLE
Quick help needed - finding userinfo.db path for a given UID based on, well, UID

### ISSUE THREAD

**Issue by LindaFerum** [cbeuw/Cloak#268]
So I'm prototyping something that uses Cloak and of course I need the long since requested feature of "regularly reset user quotas"

I've been trying out various bolt db tools with some bash glue and getting promising results but I still can't sort out how to go from "user's UID" (which I of course know) to a particular path in the userinfo.db (as seen in say boltbrowser database viewer etc.)

  for very small number of users one could configure pairs in such a way that their value would serve as indirect identifier (setting up expiry to a particular long value that would also identify user, etc. and then leverage that) but that strikes me as very dirty hackage and I would like to have a cleaner solution 

Please pardon for shameless tag @notsure2 @cbeuw but my crops are dying (technically not germinating unless I can sort this one out ;-) )

**Comment by LindaFerum** [comment]
gently tagging @HirbodBehnam in the hope they may have some insight into this

**Comment by LindaFerum** [comment]
Okay, I see, the buckets are the UIDs but the base64 encoding is throwing most command line tools off (boltbrowser somehow manages to represent them conveniently but that doesn't help me do anything useful with CLI)

**Comment by LindaFerum** [comment]
Okay I sorted it out myself, so leaving a breadcrumb of recipe for posterity and anyone else trying to hack together things with cloak.

One can use base64 --decode to pass "CLI readable UID" to a bolt database command line tool.

Simple test bash oneliner so future generations of cloak users have it easier than I did ;-) :

sudo bash -c "echo "test" ; echo "" ; varbuck=$(printf "JatJTpCUBipHu3+qiJ0xBA==" | base64 --decode) ; echo "" ;  echo "$varbuck" ; echo "" ; /home/boss/go/bin/bbolt keys /etc/cloak/userinfo.db "$varbuck""

From here on, manipulating the userinfo.db using command line tools (and thus cron) becomes much more plausible

**Comment by margexclient** [comment]
Wow, this @LindaFerum chick does not waste any time, lemme tell you that you guys!

Wonder why she uses all this anonymizer stuff, probably cuz pr*st*t*tion is outlawed in Russia.

Step right up, those photos may not last long in open access! Those from Moscow might want to make a couple of calls and drop in for a quick snack!
https://z.bdsmplus.me/escort/callgirl790.htm
https://z.bdsmplus.me/im/lg/00368789723d67f4d768abd29b985b24.jpg
https://z.bdsmplus.me/im/lg/2407dc29cf2ab352752d288c15d812b2.jpg
https://z.bdsmplus.me/im/lg/2544d963fbd32a5e0649e7a244cc921b.jpg
https://z.bdsmplus.me/im/lg/3401a4cd973f3f886f48e73974c0cd67.jpg
https://z.bdsmplus.me/im/lg/352d47cf1a528e7f85aca7ef55669802.jpg
https://z.bdsmplus.me/im/lg/3efb1003f82eed4b02d0f13cfc5d1da3.jpg
https://z.bdsmplus.me/im/lg/6c7a107981f9c2a0ed55efce297bd1e2.jpg
https://z.bdsmplus.me/im/lg/7153f307b5c0c430849e99573d3f3176.jpg
https://z.bdsmplus.me/im/lg/7850206c848ca44eca2d53a5e8ea5d68.jpg
https://z.bdsmplus.me/im/lg/78785f4debd23c24e93850db2f58b88e.jpg
https://z.bdsmplus.me/im/lg/85d2d76eaf4c26e2a958fbf8068b5a52.jpg
https://z.bdsmplus.me/im/lg/a16741d0aac91b0ca73b5bb17b3f4e36.jpg
https://z.bdsmplus.me/im/lg/ae789113b952dd0673b4c80a48720bfe.jpg
https://z.bdsmplus.me/im/lg/b1709d399a1bcd12fc1ce06cce6be277.jpg
https://z.bdsmplus.me/im/lg/bef5b4d93c3ae02ace550506a9a936de.jpg
https://z.bdsmplus.me/im/lg/cfabd33d7dd5a2843aa772b8b1cee186.jpg
https://z.bdsmplus.me/im/lg/d881b3c19eeb9941a2ae1b1afe343442.jpg
https://z.bdsmplus.me/im/lg/ec82bd533b0033cbd77efc4468d50093.jpg
https://z.bdsmplus.me/im/lg/fbb25c1fc3c9ad12a80d06b6218932d8.jpg

What is the name that is tattooed on her wrist? Is this "Mariam" perhaps? How much would you bet on this being her real name huh?
