### ISSUE TITLE
Shadowsocks-rust/OpenVPN + Cloak does not work on some net in rus

### ISSUE THREAD

**Issue by unixs** [cbeuw/Cloak#279]
I think today censorship devices have been updated. Cloak does not work on only one specific network.
Yesterday everything was good.

The problem occurred sequentially. First, the "plain" mode stopped working. A few days later, the encrypted mode stopped working.
```
cloak-server-1   | time="2024-09-18T18:56:04Z" level=warning msg="error reading first packet: read error after connection is established: read tcp 1.2.3.4:443->188.65.247.135:62419: i/o timeout" remoteAddr="188.65.247.135:62419"
cloak-server-1   | time="2024-09-18T18:56:04Z" level=warning msg="error reading first packet: read error after connection is established: read tcp 1.2.3.4:443->188.65.247.135:43785: i/o timeout" remoteAddr="188.65.247.135:43785"
cloak-server-1   | time="2024-09-18T18:56:04Z" level=warning msg="error reading first packet: read error after connection is established: read tcp 1.2.3.4:443->188.65.247.135:30731: i/o timeout" remoteAddr="188.65.247.135:30731"
cloak-server-1   | time="2024-09-18T18:56:04Z" level=warning msg="error reading first packet: read error after connection is established: read tcp 1.2.3.4:443->188.65.247.135:13623: i/o timeout" remoteAddr="188.65.247.135:13623"
```

**Comment by LindaFerum** [comment]
I think you might want to change you server's IP

Also, by "plain" you mean Cloak's plain? Why use that in prod at all?

**Comment by unixs** [comment]
According to readme:

> EncryptionMethod is the name of the encryption algorithm you want Cloak to use. Options are plain, aes-256-gcm ( synonymous to aes-gcm), aes-128-gcm, and chacha20-poly1305. Note: **Cloak isn't intended to provide transport security**. The point of encryption is to hide fingerprints of proxy protocols and render the payload statistically random-like. **You may only leave it as plain if you are certain that your underlying proxy tool already provides BOTH encryption and authentication (via AEAD or similar techniques).**

I will check it with new ip ASAP

**Comment by LLIycTpbIu** [comment]
Same here, ss+cloak with aes-256-cfb cypher, doesn`t work on network of my mobile operator anymore

**Comment by cbeuw** [comment]
One probable way to detect Cloak has been monitoring packet sizes for encapsulated TLS handshakes, so that could be what's happening here. The latest release (v2.10.0) could help as I've added random padding

**Comment by LLIycTpbIu** [comment]
@cbeuw Now it works at release (v2.10.0) builded from sources, downloaded version of binary doesn`t work.
Thank you!

**Comment by cbeuw** [comment]
Huh that's very strange, the releases are built by CI. Could you upload the binary you built? I'm curious about the difference.

**Comment by LLIycTpbIu** [comment]
here
[ck-server_2.10.zip](https://github.com/user-attachments/files/17364243/ck-server_2.10.zip)

**Comment by LLIycTpbIu** [comment]
It works, but randomly, I tried many times to connect and disconnect client on Android, 2/10 - connected, 8/10 connectrion refused.

**Comment by unixs** [comment]
All works fine with same provider.
Server version 2.10.0 from github.
