### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by hybtoy** [cbeuw/Cloak#28]
@cbeuw 
Hey. Thanks for the plugin. It seems to work faster that ssr  with auth_chain_a+ tls1.2 ticket auth for me now, will continue to test it. 

The problem is that I can not fully understand how to add new users. 

I understand that I have to generate new UID as at mentioned in the Readme of this repo but what about Public and Private Keys? Are they same for all users or we have to provide separate Public and Private key for each user (UID)? If YES, how to do that in proper way? 

Thanks.

**Comment by cbeuw** [comment]
The public and private keys are the same for every user
