### ISSUE TITLE
Installer Script Not Working on Centos 7

### ISSUE THREAD

**Issue by HirbodBehnam** [cbeuw/Cloak#29]
Hello
At first, your plugin is great! Shadowsocks is throttled in some ISPs in Iran. I used to get around 400 kbit/s but with cloak the speed is boosted to 40Mbit/s.
The script you provided [here](https://gist.github.com/cbeuw/37a9d434c237840d7e6d5e497539c1ca) is not installing shadowsocks-libev for CentOS 7 because `dnf` is not installed by default.
Therefore, I have rewritten a script from scratch (well somehow). Here is the [link](https://github.com/HirbodBehnam/Shadowsocks-Cloak-Installer). If you like you can put this in your page. It also creates QR Code and `ss://` link at the end of it. I supports Debian 8/9, Ubuntu 16~19 and Centos 7. I will add other features later.

Plus if you have an Ethereum wallet, I am ready to donate to you!

**Comment by cbeuw** [comment]
The script works amazingly. Thanks!

**Comment by hybtoy** [comment]
@HirbodBehnam what about multi-user support?

**Comment by HirbodBehnam** [comment]
@cbeuw
You're welcome! If you like you can share your wallet so I can send you some small money!

@hybtoy
Sure! I will add it as soon as I can!

**Comment by HirbodBehnam** [comment]
Sry @cbeuw 
I haven't fully read the readme!
I will send you some ETH as soon as I can

**Comment by cbeuw** [comment]
@HirbodBehnam much appreciated!
