### ISSUE TITLE
multi Ips

### ISSUE THREAD

**Issue by malikshi** [cbeuw/Cloak#31]
`{
		"WebServerAddr":"204.79.197.200:443",
		"PrivateKey":"EN5aPEpNBO+vw+BtFQY2OnK9bQU7rvEj5qmnmgwEtUc=",
		"AdminUID":"ugDmcEmxWf0pKxfkZ/8EoP35Ht+wQnqf3L0xYgyQFlQ=",
		"DatabasePath":"userinfo.db",
		"BackupDirPath":""
}`
can we use IPs in this section 
> "WebServerAddr":"204.79.197.200:443",

become

>"WebServerAddr":"204.79.197.200:443;a.b.c.d:443;e.f.g.h:443",

?

**Comment by cbeuw** [comment]
No it doesn't support that format. But what do you want to achieve with putting multiple addresses?

**Comment by malikshi** [comment]
> No it doesn't support that format. But what do you want to achieve with putting multiple addresses?

so its doesn needed to launch new server cloak again, just asking possibility.

and today i got somehow more RAM usage in my server.
here my spec 
ubuntu 18.04
bbr active
RAM 1GB SWAP 2GB,
everything was normal with shadowsocks old version from ubuntu repo. but i try installing new version of shadowsocks 3.3.0 but the ram usage is not effecient or what? only 2 server cloak running on my vps
but after some minutes `free -m` only avaible ram 100-200MB and server error after that when hit available ram 70MB.
![Screenshot_29](https://user-images.githubusercontent.com/9080737/59650412-83a2b800-91b8-11e9-9791-bff73143c307.jpg)
