### ISSUE TITLE
Where is config/ckserver.json ?

### ISSUE THREAD

**Issue by obvioususername** [cbeuw/Cloak#32]
I downloaded Ck-server-linux-amd64-1.1.1 on Ubuntu 18.04 and was trying to set the server up, but i couldn't find the ckserver.json file. Do i creat the json file locally or do i download it from somewhere or i'm just too dumb to find it lol ?

**Comment by cbeuw** [comment]
Example configs can be found here: https://github.com/cbeuw/Cloak/tree/master/config

Note that you need to generate your own UID and key pairs

**Comment by obvioususername** [comment]
Thanks , but i ran into a new problem that stopping SS-libev server with Cloak from starting. 
It seems like the same problem with the Issue 13.  i've read it, however after many attempt, i still failed to fix it.
The OS  it runs on is Ubuntu 18.04
Here is the ckserver.json :
{
                "WebServerAddr":"54.222.60.218:443",
                "PrivateKey":"myprivatekey",
                "AdminUID":"myUID",
                "DatabasePath":"/root/Cloak/config/userinfo.db",
                "BackupDirPath":"/root/Cloak/config/db-backup/userinfo.db"
}

And here is the SS-libev server config.json
{
    "server":"myserver",
    "server_port":443,
    "local_port":1080,
    "password":"mypassword",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "plugin":"/root/Cloak",
    "plugin_opts":"/root/Cloak/config/ckserver.json"
}

The ck-server file is located at /root/Cloak
I use systemtcl to start ss-server.
Here is some info from systemctl status:
 Started Shadowsocks-libev Default Server Service.
 ss-server[3657]: sh: 1: exec: /root/Cloak: Permission denied
 ERROR: plugin service exit unexpectedly
 INFO: plugin "/root/Cloak" enabled
 INFO: UDP relay enabled
 INFO: initializing ciphers... chacha20-ietf-po

**Comment by HirbodBehnam** [comment]
Hello
As you can clearly see there is a permission problem. You can fix this by editing shadowsocks-libev.service file. To find out where the file is run `systemctl status shadowsocks-libev`.  Then for me (Centos 7) it says:
```
 shadowsocks-libev.service - Shadowsocks-libev Default Server Service
 Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; disabled; vendor preset: disabled)
```
You can see that my service file is in `/usr/lib/systemd/system/shadowsocks-libev.service`. Open the file with your favorite editor. Then there are two line like this:
```
User=nobody
Group=nobody
```
Change them to
```
User=root
Group=root
```
Then save and exit. Run `systemctl daemon-reload` and then `systemctl restart shadowsocks-libev` and see if the problem is fixed or not.

Also as mentioned in readme, I have written a small script to automatically install Shadowsocks with Cloak with just some clicks. You can try that if you like.

**Comment by obvioususername** [comment]
Hello
I followed your suggestion but it didn't work on me. It still failed to start with permisson denied error.

**Comment by obvioususername** [comment]
> 
> 
> Hello
> As you can clearly see there is a permission problem. You can fix this by editing shadowsocks-libev.service file. To find out where the file is run `systemctl status shadowsocks-libev`. Then for me (Centos 7) it says:
> 
> ```
>  shadowsocks-libev.service - Shadowsocks-libev Default Server Service
>  Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; disabled; vendor preset: disabled)
> ```
> 
> You can see that my service file is in `/usr/lib/systemd/system/shadowsocks-libev.service`. Open the file with your favorite editor. Then there are two line like this:
> 
> ```
> User=nobody
> Group=nobody
> ```
> 
> Change them to
> 
> ```
> User=root
> Group=root
> ```
> 
> Then save and exit. Run `systemctl daemon-reload` and then `systemctl restart shadowsocks-libev` and see if the problem is fixed or not.
> 
> Also as mentioned in readme, I have written a small script to automatically install Shadowsocks with Cloak with just some clicks. You can try that if you like.

**Comment by obvioususername** [comment]
> 
> 
> Hello
> As you can clearly see there is a permission problem. You can fix this by editing shadowsocks-libev.service file. To find out where the file is run `systemctl status shadowsocks-libev`. Then for me (Centos 7) it says:
> 
> ```
>  shadowsocks-libev.service - Shadowsocks-libev Default Server Service
>  Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; disabled; vendor preset: disabled)
> ```
> 
> You can see that my service file is in `/usr/lib/systemd/system/shadowsocks-libev.service`. Open the file with your favorite editor. Then there are two line like this:
> 
> ```
> User=nobody
> Group=nobody
> ```
> 
> Change them to
> 
> ```
> User=root
> Group=root
> ```
> 
> Then save and exit. Run `systemctl daemon-reload` and then `systemctl restart shadowsocks-libev` and see if the problem is fixed or not.
> 
> Also as mentioned in readme, I have written a small script to automatically install Shadowsocks with Cloak with just some clicks. You can try that if you like.

Hello
I followed your suggestion but it didn't work on me. It still failed to start with permisson denied error.

**Comment by HirbodBehnam** [comment]
Ok can you run `ss-server` from root user?

**Comment by obvioususername** [comment]
Yes, it shows error as well : 
 INFO: initializing ciphers... chacha20-ietf-poly1305
 INFO: tcp server listening at 172.96.223.4:443
 ERROR: bind: Address already in use
 ERROR: bind() error

**Comment by obvioususername** [comment]
> 
> 
> Ok can you run `ss-server` from root user?
> Just type and execute `ss-server`

Yes, it shows error as well :
INFO: initializing ciphers... chacha20-ietf-poly1305
INFO: tcp server listening at A.B.C.D:443
ERROR: bind: Address already in use
ERROR: bind() error

**Comment by HirbodBehnam** [comment]
See looks like something is using 443 port.
Can you post the output of this?

`netstat -ltnp | grep -w ':443' `

If `netstat` is not installed try installing it by `apt install net-tools`

**Comment by obvioususername** [comment]
Oh, i was running vanilla SS when i ran ss-server command, so the 443 port is occupied.
I stopped it and tried again with Cloak. Output's below :
 INFO: plugin "/root/Cloak" enabled
 INFO: initializing ciphers... chacha20-ietf-poly1305
 INFO: tcp server listening at 127.0.0.1:45371
 INFO: running from root user
 sh: 1: exec: /root/Cloak: Permission denied
 ERROR: plugin service exit unexpectedly
(I omitted dates and time stamp)

**Comment by obvioususername** [comment]
> 
> 
> See looks like something is using 443 port.
> Can you post the output of this?
> 
> `netstat -ltnp | grep -w ':443' `
> 
> If `netstat` is not installed try installing it by `apt install net-tools`
> 
> This command shows what application is using the 443 port.
> 
> As an alternative way you can change the port of proxy to something else.

Oh, i was running vanilla SS when i ran ss-server command, so the 443 port is occupied.
I stopped it and tried again with Cloak. Output's below :
INFO: plugin "/root/Cloak" enabled
INFO: initializing ciphers... chacha20-ietf-poly1305
INFO: tcp server listening at 127.0.0.1:45371
INFO: running from root user
sh: 1: exec: /root/Cloak: Permission denied
ERROR: plugin service exit unexpectedly
(I omitted dates and time stamp)

**Comment by HirbodBehnam** [comment]
I'm not sure about this but you can try:
`chmod -R 777 /root/Cloak`
This command makes /root/Cloak folder and it's subfiles world accessible.

As an alternative method you can try moving /root/Cloak folder somewhere that is global accessible.

**Comment by obvioususername** [comment]
> 
> 
> I'm not sure about this but you can try:
> `chmod -R 777 /root/Cloak`
> This command makes /root/Cloak folder and it's subfiles world accessible.
> 
> As an alternative method you can try moving /root/Cloak folder somewhere that is global accessible.

I tried but still same result unfortunately.  :(

**Comment by HirbodBehnam** [comment]
Ok can you use [this](https://github.com/HirbodBehnam/Shadowsocks-Cloak-Installer) script to install the Shadowsocks with Cloak?

**Comment by cbeuw** [comment]
Don't put anything under /root. That's the home directory of the root user and you will run into permission problems for almost everything. Ideally you should put Cloak under your own home directory, that's /home/[your user name]

**Comment by obvioususername** [comment]
> 
> 
> Don't put anything under /root. That's the home directory of the root user and you will run into permission problems for almost everything. Ideally you should put Cloak under your own home directory, that's /home/[your user name]

I did that and the SS server with cloak started, but when i edited the SS windows client's server info,  i clicked "OK", then i got some error pops out(which i forgot to save those texts). When i went to the SS server side, i see errors like these :
ERROR: block all requests from A.B.C.D(the IP of my local PC)
ERROR: block all requests from A.B.C.D
ERROR: block all requests from A.B.C.D
ERROR: block all requests from A.B.C.D
ERROR: block all requests from A.B.C.D
ERROR: block all requests from A.B.C.D
ERROR: block all requests from A.B.C.D
ERROR: block all requests from A.B.C.D
ERROR: block all requests from A.B.C.D
ERROR: block all requests from A.B.C.D

Then i restarted SS-server with Cloak , there is permisson denied problem again : 
sh: 1: exec: /home/peiper/cloak: Permission denied
 ERROR: plugin service exit unexpectedly
 INFO: plugin "/home/peiper/cloak" enabled
 INFO: UDP relay enabled
 INFO: initializing ciphers... chacha20-ietf-pol
 INFO: tcp server listening at 127.0.0.1:44027
 INFO: udp server listening at 172.96.223.4:443

**Comment by cbeuw** [comment]
Try `chmod +x /home/peiper/cloak`?

**Comment by obvioususername** [comment]
> 
> 
> Try `chmod +x /home/peiper/cloak`?

Not working, same error. :(

**Comment by obvioususername** [comment]
> 
> 
> Try `chmod +x /home/peiper/cloak`?

Is there something wrong with the path in my ckserver.json ?


{
                "WebServerAddr":"54.222.60.218:443",
                "PrivateKey":"myprivatekey",
                "AdminUID":"myUID",
                "DatabasePath":"/home/peiper/cloak/userinfo.db",
                "BackupDirPath":"/home/peiper/cloak"
}

**Comment by cbeuw** [comment]
What is `/home/peiper/cloak`? Is it a directory or is it an executable? If it's a directory then it can't be executed. You need to set `plugin` to the executable file of ck-server. If it's an executable then you can't do `/home/peiper/cloak/userinfo.db`

**Comment by obvioususername** [comment]
> 
> 
> What is `/home/peiper/cloak`? Is it a directory or is it an executable? If it's a directory then it can't be executed. You need to set `plugin` to the executable file of ck-server. If it's an executable then you can't do `/home/peiper/cloak/userinfo.db`

/home/peiper/cloak is a directory that contains the ck-server file and ckserver.json.
I redo the `plugin`field in the SS-server's config.json , but it still failed to start. Got error like this : 
Configuration file error: Attempting to open database: open /home/peiper/cloak/userinfo.db: permission denied

 These are the plugin and plugin_opts filed in ss-server's config.json : 
    "plugin":"/home/peiper/cloak/ck-server-linux-amd64-1.1.1",
    "plugin_opts":"/home/peiper/cloak/ckserver.json"

**Comment by cbeuw** [comment]
Delete userinfo.db and let Cloak create one itself again. It may have been created with root privilege and doesn't let cloak write

**Comment by obvioususername** [comment]
> 
> 
> Delete userinfo.db and let Cloak create one itself again. It may have been created with root privilege and doesn't let cloak write

I ran `find / userinfo.db` , but the output is "No such file or directory"

**Comment by obvioususername** [comment]
> 
> 
> Delete userinfo.db and let Cloak create one itself again. It may have been created with root privilege and doesn't let cloak write

Well, i created the `/peiper` directory under`/home` whit root identity expecting to avoid the permisson problem, but it seems not working. May be it's because i'm logged in as root ? Should i make a new user to try again ?

**Comment by cbeuw** [comment]
Urghhh... Why did you manually create a directory under /home? The users' home folders should have be automatically created when you create a user.

In almost all situation you shouldn't log in as root. Didn't the system prompt you to create a user when you installed Ubuntu? Regardless if you don't have a user other than root, you should create one and never log in as root again. If you need superuser privilege, use sudo.

**Comment by obvioususername** [comment]
> 
> 
> Urghhh... Why did you manually create a directory under /home? The users' home folders should have be automatically created when you create a user.
> 
> In almost all situations you shouldn't log in as root. Didn't the system prompt you to create a user when you installed Ubuntu? Regardless if you don't have a user other than root, you should create one and never log in as root again. If you need superuser privilege, use sudo.

What a fool i am. lol 
Anyway, i  created and logged in as a new sudo user `peiper`, then did it all over again, but fortunately there is still permisson denied error like before in systemctl status. Besides when i run `ss-server` there is output like this indicates something wrong with the private key : 

` INFO: plugin "/home/peiper/cloak/ck-server-linux-amd64-1.1.1" enabled
  INFO: initializing ciphers... chacha20-ietf-poly1305
  INFO: tcp server listening at 127.0.0.1:53031
  ck-server.go:254: Configuration file error: Failed to decode private key: illegal base64 data at input byte   32
  ERROR: plugin service exit unexpectedly`

**Comment by cbeuw** [comment]
Make sure to include the = paddings at the end when copying base64 strings. They are necessary.

**Comment by obvioususername** [comment]
> 
> 
> Make sure to include the = paddings at the end when copying base64 strings. They are necessary.

Hi 
I generated new keys and UID then set up again, it worked ! The proxy speed skyrocketed.
But there is still a problem that it can not be start by systemctl which will get permission denied to userinfo.db error. Using `ss-server` works perfectly but once i exit SSH terminal, it's dead.
I'm sorry to be annoying, is there any possible solution ?

**Comment by obvioususername** [comment]
> 
> 
> > Make sure to include the = paddings at the end when copying base64 strings. They are necessary.
> 
> Hi
> I generated new keys and UID then set up again, it worked ! The proxy speed skyrocketed.
> But there is still a problem that it can not be start by systemctl which will get permission denied to userinfo.db error. Using `ss-server` works perfectly but once i exit SSH terminal, it's dead.
> I'm sorry to be annoying, is there any possible solution ?

Oh wait, it seems `ss-server` keeps working after i log out my server, does it keeps running in background by default ? Should i do something like put `nohup &`on that command to make sure it runs after exitting terminal ?

**Comment by HirbodBehnam** [comment]
Hello
You have two options.
1. Use `tmux` or `screen`. These applications make the process run in background even if the SSH connection is closed.
I personally sometimes use `tmux`. Just install it via your package manager and then type `tmux` in terminal. Then type `ss-server`. You will see that the ss-server starts running. Press `Ctrl+B` and then press `D`. The session will be detached and you can safely close the SSH connection. However if you reboot your server you have to do it again.

2. Use a service.
If you want systemctl service you can try this:
At first type `nano /etc/systemd/system/shadowsocks-server.service`. This will open the nano editor. Then paste this inside it:
```
[Unit]
Description=Shadowsocks-libev Server Service
Documentation=man:shadowsocks-libev(8)
After=network.target network-online.target

[Service]
Type=simple
User=root
Group=root
LimitNOFILE=32768
ExecStart=/usr/bin/ss-server
WorkingDirectory=/etc/shadowsocks-libev

[Install]
WantedBy=multi-user.target
```
**Note:** You may change some values in this file like User and Group or even WorkingDirectory.
After you saved this, type `systemctl daemon-reload` and then `systemctl start shadowsocks-server` and `systemctl enable shadowsocks-server`

**Comment by obvioususername** [comment]
> 
> 
> Hello
> You have two options.
> 
>     1. Use `tmux` or `screen`. These applications make the process run in background even if the SSH connection is closed.
>        I personally sometimes use `tmux`. Just install it via your package manager and then type `tmux` in terminal. Then type `ss-server`. You will see that the ss-server starts running. Press `Ctrl+B` and then press `D`. The session will be detached and you can safely close the SSH connection. However if you reboot your server you have to do it again.
> 
>     2. Use a service.
>        If you want systemctl service you can try this:
>        At first type `nano /etc/systemd/system/shadowsocks-server.service`. This will open the nano editor. Then paste this inside it:
> 
> 
> ```
> [Unit]
> Description=Shadowsocks-libev Server Service
> Documentation=man:shadowsocks-libev(8)
> After=network.target network-online.target
> 
> [Service]
> Type=simple
> User=root
> Group=root
> LimitNOFILE=32768
> ExecStart=/usr/bin/ss-server
> WorkingDirectory=/etc/shadowsocks-libev
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> **Note:** You may change some values in this file like User and Group or even WorkingDirectory.
> After you saved this, type `systemctl daemon-reload` and then `systemctl start shadowsocks-server` and `systemctl enable shadowsocks-server`

Thanks for the help !

**Comment by HirbodBehnam** [comment]
You're welcome :)
