### ISSUE TITLE
Cloak with CDN

### ISSUE THREAD

**Issue by HirbodBehnam** [cbeuw/Cloak#33]
Hello
Is it possible to use Cloak with a CDN like cloudflare?
I successfully done it with V2Ray HTTP websocket mode to route my traffic through cloudflare. It is possible to do the same thing with cloak?
I am running cloak on port 443, AES-128-GCM and even tried to set my `ServerName` to my cloudflare domain. (The one that I assigned in cloudflare)

**Comment by malikshi** [comment]
would u try
client config
server use IPs from cloudflare, and fill Servename with your domain. but i dont think its will work, maybe you should using v2ray if wanna throught cdn like cloudflare.

**Comment by HirbodBehnam** [comment]
Yeah v2ray was fine but cloak was not OK
I was just asking if it was possible or not
