### ISSUE TITLE
Question on domain to use OBFS

### ISSUE THREAD

**Issue by yagigain** [cbeuw/Cloak#35]
Quick question, I think I know the answer.

Would it be better to use a domain for the OBFS that resolves to the same IP used for the SS server ?  

The default in the config is bing, but this wouldn't work as well as a domain resolving to SS IP ?    

Or doesn't it matter with Cloak ?

**Comment by cbeuw** [comment]
Ideally the domain name should resolve to the `WebServerAddr` field in ck-server configuration. But this doesn't affect the functionalities of Cloak.

**Comment by yagigain** [comment]
ok thanks ... but it dosn't help to have it on the same IP as "server' in config.json (for SS) ?     Like with V2Ray you have the webserver on the IP of SS using reverse proxy to share the port.

**Comment by cbeuw** [comment]
If you are running a webserver on the host, then yes you can leave it as the address of your webserver. But note it should be a localhost address. If you leave it as your public IP a.b.c.d:443, then ck-server will redirect the traffic back to ck-server causing an infinite loop.
