### ISSUE TITLE
undefined: syscall.RawConn

### ISSUE THREAD

**Issue by beanslel** [cbeuw/Cloak#36]
Trying to build the client with `make client` from the latest source I get the following error:

```
~/go/src/github.com/cbeuw/Cloak$ make client
mkdir -p build
go build -ldflags "-X main.version=master(8317f44)" ./cmd/ck-client
# github.com/cbeuw/Cloak/cmd/ck-client
cmd/ck-client/protector.go:7: undefined: syscall.RawConn
Makefile:10: recipe for target 'client' failed
make: *** [client] Error 2
```

Building the server with `make server` works fine. 
Is the function in protector.go required, since it is empty?

Using `go version go1.7.4 linux/amd64`

**Comment by cbeuw** [comment]
Go 1.7 is too old. Building ck-client requires 1.11+

**Comment by beanslel** [comment]
Yep.. my bad. Installing the latest go version solved it. Thank you!
