### ISSUE TITLE
SS with Cloak constantly stops working

### ISSUE THREAD

**Issue by obvioususername** [cbeuw/Cloak#37]
My SS-Server OS : Ubuntu 18.04 LTS (GNU/Linux 4.15.0-20-generic x86_64)
My Local OS : Windows 7 Home
My applications version : Shaowsocks-libev server 3.3.0 with Cloak plugin
                                       Shadowsocks Windows client 4.1.6 with Cloak plugin

The problem is that the proxy speed drops dramatically(can't load web pages at all) every few minutes or just time out.
Sometimes the proxy wouldn't work when i open the browser even i never turn off the ss client.

Two workaround i found are :
A. Switch my SS client proxy mode from Global to Pac then switch back. Sometimes  i have to switch'em back and forth until it works lol .
B. Restart Shadowsocks client, but it doesn't work every time.

If i leave it be and do nothing about it, it sometimes it goes back to normal in few minutes, sometime it just stay dead until i perform CPR(the workround lol) to it.
Besides, i found out that when the SS proxy goes extremely slow or failed, so does the SSH connection to my remote server. However, the connectivity testing result of my remote server is all good.
PS. i have set the Timeout on ss server and client into 5 sec, it's better than before a little bit, but the problem's still there.

**Comment by malikshi** [comment]
does windows 7 support system proxy GLOBAL mode ?

**Comment by cbeuw** [comment]
Can you run Cloak in standalone mode in cmd and see the log?

**Comment by obvioususername** [comment]
> 
> 
> does windows 7 support system proxy GLOBAL mode ?

I have no idea, should it ?

**Comment by obvioususername** [comment]
> 
> 
> Can you run Cloak in standalone mode in cmd and see the log?

Ok , how do i run standalone mode and where can i find the log ?

**Comment by cbeuw** [comment]
In shadowsocks client, duplicate the current profile you are using and change the server to 127.0.0.1, the port to one of your liking (say 8388). Clear the plugin and plugin_opts fields

Open up cmd, go into the directory of ck-client.exe, run ck-client -s [IP of your server] -l 8388 -c [path to config file]

Logs will then be printed to the cmd window

**Comment by obvioususername** [comment]
> 
> 
> In shadowsocks client, duplicate the current profile you are using and change the server to 127.0.0.1, the port to one of your liking (say 8388). Clear the plugin and plugin_opts fields
> 
> Open up cmd, go into the directory of ck-client.exe, run ck-client -s [IP of your server] -l 8388 -c [path to config file]
> 
> Logs will then be printed to the cmd window

Here's the log : 
`2019/07/07 16:31:07 ck-client.go:131: Starting standalone mode
2019/07/07 16:31:07 ck-client.go:168: Listening for ss on 127.0.0.1:8
2019/07/07 16:31:07 ck-client.go:174: Attemtping to start a new sessi
2019/07/07 16:31:09 ck-client.go:204: Session 1438396682 established
2019/07/07 16:32:06 ck-client.go:174: Attemtping to start a new sessi
2019/07/07 16:32:06 ck-client.go:225: broken session
2019/07/07 16:32:10 ck-client.go:204: Session 1570754861 established
2019/07/07 16:33:56 ck-client.go:174: Attemtping to start a new sessi
2019/07/07 16:33:56 ck-client.go:225: broken session
2019/07/07 16:33:57 ck-client.go:204: Session 558097203 established
2019/07/07 16:34:46 ck-client.go:174: Attemtping to start a new sessi
2019/07/07 16:34:46 ck-client.go:225: broken session
2019/07/07 16:34:52 ck-client.go:204: Session 1394925037 established
2019/07/07 16:45:38 ck-client.go:231: write tcp 192.168.1.101:56253->
6:443: use of closed network connection
2019/07/07 16:46:53 ck-client.go:231: write tcp 192.168.1.101:56254->
6:443: use of closed network connection
2019/07/07 16:46:53 ck-client.go:231: write tcp 192.168.1.101:56254->
6:443: wsasend: An existing connection was forcibly closed by the remote host.
2019/07/07 16:46:54 ck-client.go:231: write tcp 192.168.1.101:56255->
6:443: wsasend: An existing connection was forcibly closed by the rem
2019/07/07 16:46:54 ck-client.go:231: write tcp 192.168.1.101:56255->
6:443: use of closed network connection
2019/07/07 16:46:54 ck-client.go:231: write tcp 192.168.1.101:56255->
6:443: use of closed network connection
2019/07/07 16:46:59 ck-client.go:174: Attemtping to start a new sessi
2019/07/07 16:46:59 ck-client.go:225: broken session
2019/07/07 16:47:00 ck-client.go:204: Session 1446117769 established
2019/07/07 16:47:44 ck-client.go:174: Attemtping to start a new sessi
2019/07/07 16:47:44 ck-client.go:225: broken session
2019/07/07 16:47:45 ck-client.go:204: Session 1131773671 established`

The problem's still there during standalone mode. By the way i'm experencing a weird thing that a certain youtube page i visit very often can't be opened without serveral try in most of the time, while any ohther youtube pages are fine. 
PS.  From 16:45:38 to 16:46:54 i did a speed test, that's probably why those text pops up.

**Comment by cbeuw** [comment]
It looks like your computer is having trouble maintaining the underlying TCP connections with the server. Can you try to use Cloak on another network, like the wifi of a cafe or something and see if the problem still exists?

**Comment by obvioususername** [comment]
> 
> 
> It looks like your computer is having trouble maintaining the underlying TCP connections with the server. Can you try to use Cloak on another network, like the wifi of a cafe or something and see if the problem still exists?

I'd like to do that but i can't at this moment or in near future  :-(

**Comment by obvioususername** [comment]
> 
> 
> It looks like your computer is having trouble maintaining the underlying TCP connections with the server. Can you try to use Cloak on another network, like the wifi of a cafe or something and see if the problem still exists?

Is there another way?

**Comment by cbeuw** [comment]
Here's another idea: pick a website that normally gets a decent amount a traffic (e.g. YouTube), set `WebServerAddr` field of ck-server to be the IP address of this website (use ping to find out it's IP), then edit the host file on your win7 computer so that the domain of the website points to the IP of your SS server. Browse this website for a while and see how stable it is. If this also has issues then I suspect that maybe the ISP is disrupting the traffic to and from your SS server

**Comment by obvioususername** [comment]
> 
> 
> Here's another idea: pick a website that normally gets a decent amount a traffic (e.g. YouTube), set `WebServerAddr` field of ck-server to be the IP address of this website (use ping to find out it's IP), then edit the host file on your win7 computer so that the domain of the website points to the IP of your SS server. Browse this website for a while and see how stable it is. If this also has issues then I suspect that maybe the ISP is disrupting the traffic to and from your SS server

Ok, do i need to edit `ServerName` in ckclient.json to Youtube ?

**Comment by cbeuw** [comment]
Yup that as well

**Comment by obvioususername** [comment]
> 
> 
> Yup that as well

I did that and the proxy's not working at all, every webpage i opened just keep loading until it time out.
Here's the SS log if you wanna take a look : 
 2019-07-08 06:36:46 INFO: plugin "/home/peiper/cloak/ck-server-linux-amd64-1.1.1" 

enabled
2019-07-08 06:36:46 INFO: initializing ciphers... chacha20-ietf-poly1305
2019-07-08 06:36:46 INFO: tcp server listening at 127.0.0.1:37091
2019-07-08 06:36:46 INFO: running from root user
2019/07/08 06:36:46 ck-server.go:265: Listening on *.*.*.*:443
2019/07/08 06:36:53 ck-server.go:142: write tcp *.*.*.*:443->*.*.*.*:10304: write:            
connection reset by peer
2019/07/08 06:36:53 ck-server.go:142: write tcp *.*.*.*:443->*.*.*.*:10240: write:            
connection reset by peer
2019/07/08 06:36:53 ck-server.go:142: write tcp *.*.*.*:443->*.*.*.*:10432: write:            
connection reset by peer
2019/07/08 06:39:54 ck-server.go:142: write tcp *.*.*.*:443->*.*.*.*:9408: write:            
connection reset by peer
2019/07/08 06:39:54 ck-server.go:142: write tcp *.*.*.*:443->*.*.*.*:9472: write:            
connection reset by peer

**Comment by chenshaoju** [comment]
I have the same issue.

Sometimes, The proxy connect is get stuck, After 5min~40 min It can back to normal. At the server, The log says:
`Jul 11 23:47:08 debian-s-1vcpu-1gb-lon1-01 ss-server[2071]:  2019-07-11 23:47:08 ERROR: server recv: Connection reset by peer`

Same `ServerName` config never happens in GoQuite.

It looks like server-side ss-server <-> ck-server have a communication issue or something else.

**Comment by yangwe1** [comment]
> I have the same issue.
> 
> Sometimes, The proxy connect is get stuck, After 5min~40 min It can back to normal. At the server, The log says:
> `Jul 11 23:47:08 debian-s-1vcpu-1gb-lon1-01 ss-server[2071]: 2019-07-11 23:47:08 ERROR: server recv: Connection reset by peer`
> 
> Same `ServerName` config never happens in GoQuite.
> 
> It looks like server-side ss-server <-> ck-server have a communication issue or something else.

Totally same here. I started using Cloak last night and a few moment later the issue came out.

The server was setup by using [this script](https://github.com/HirbodBehnam/Shadowsocks-Cloak-Installer/blob/master/Shadowsocks-Cloak-Installer.sh) in tutorial. The only modified param is _NumConn_ which I'm not sure the meanning of was set to 40.

Here's the log:

```
Jul 24 11:32:16 ubuntu ss-server[17846]: 2019/07/24 11:32:16 ck-server.go:74: +1 non SS TLS traffic from 146.88.240.44:50436
Jul 24 11:48:03 ubuntu ss-server[17846]: 2019/07/24 11:48:03 ck-server.go:67: +1 non SS non (or malformed) TLS traffic from 110.167.90.154:6463
Jul 24 11:48:03 ubuntu ss-server[17846]: 2019/07/24 11:48:03 ck-server.go:67: +1 non SS non (or malformed) TLS traffic from 123.191.148.85:46431
Jul 24 11:48:03 ubuntu ss-server[17846]: 2019/07/24 11:48:03 ck-server.go:67: +1 non SS non (or malformed) TLS traffic from 36.5.178.67:1990
Jul 24 11:48:24 ubuntu ss-server[17846]: 2019/07/24 11:48:24 ck-server.go:67: +1 non SS non (or malformed) TLS traffic from 119.118.0.22:45530
Jul 24 11:58:18 ubuntu ss-server[17846]: 2019/07/24 11:58:18 ck-server.go:157: New session from UID:**HIDEN**, sessionID:1789555818
Jul 24 12:00:01 ubuntu ss-server[17846]: 2019/07/24 12:00:01 ck-server.go:163: Session closed for UID:**HIDEN**, sessionID:1789555818
Jul 24 12:22:43 ubuntu ss-server[17846]:  2019-07-24 12:22:43 ERROR: remote recv: Connection reset by peer
Jul 24 12:22:49 ubuntu ss-server[17846]:  2019-07-24 12:22:49 ERROR: remote recv: Connection reset by peer
Jul 24 12:23:29 ubuntu ss-server[17846]:  2019-07-24 12:23:29 ERROR: remote recv: Connection reset by peer
Jul 24 12:23:29 ubuntu ss-server[17846]:  2019-07-24 12:23:29 ERROR: remote recv: Connection reset by peer
Jul 24 12:24:03 ubuntu ss-server[17846]:  2019-07-24 12:24:03 ERROR: remote recv: Connection reset by peer
Jul 24 12:25:25 ubuntu ss-server[17846]:  2019-07-24 12:25:25 ERROR: remote recv: Connection reset by peer
Jul 24 12:26:09 ubuntu ss-server[17846]:  2019-07-24 12:26:09 ERROR: remote recv: Connection reset by peer
Jul 24 12:26:45 ubuntu ss-server[17846]:  2019-07-24 12:26:45 ERROR: remote recv: Connection reset by peer
Jul 24 12:27:23 ubuntu ss-server[17846]:  2019-07-24 12:27:23 ERROR: remote recv: Connection reset by peer
Jul 24 12:27:29 ubuntu ss-server[17846]:  2019-07-24 12:27:29 ERROR: remote recv: Connection reset by peer
Jul 24 12:42:55 ubuntu ss-server[17846]: 2019/07/24 12:42:55 ck-server.go:157: New session from UID:**HIDEN**, sessionID:2102431777
Jul 24 12:44:05 ubuntu ss-server[17846]: 2019/07/24 12:44:05 ck-server.go:163: Session closed for UID:**HIDEN**, sessionID:1277956778
Jul 24 13:13:06 ubuntu ss-server[17846]: 2019/07/24 13:13:06 ck-server.go:163: Session closed for UID:**HIDEN**, sessionID:2102431777
```

The scanners or rebots or something keeps annoying me...so I need a plugin like this to protect my ss server

**Comment by StevenBirdBrown** [comment]
As far as I know, the error `Connection reset by peer` often results from your ISP or firewall's attacks.

**Comment by chenshaoju** [comment]
After using Cloak 2.0.2, Everying is working fine.

Thanks.
