### ISSUE TITLE
Cant Delete UID

### ISSUE THREAD

**Issue by malikshi** [cbeuw/Cloak#38]
@cbeuw hello sir, 
one of my team mate report some issue about deleting UID got error when the UID has `/` in text.
here some example: `BCuD2N6o7o/LxzlJ02hoI54BRJRr4IWcze7cLvW0GXY=`
i tried delete that UID but no luck, here the response
> 5
Enter UID
BCuD2N6o7o/LxzlJ02hoI54BRJRr4IWcze7cLvW0GXY=
Are you sure to delete this user? y/n
y
open /etc/shadowsocks-libev/BackupDir/1562463369_pre_del_BCuD2N6o7o/LxzlJ02hoI54BRJRr4IWcze7cLvW0GXY=.bak: no such file or directory

i thought when creating backup file its has `/` that mean another folder right? all UID without `/` normal without issue when deleting those account/UID.
![Screenshot_106](https://user-images.githubusercontent.com/9080737/60762899-acbdb680-a09b-11e9-8cd6-29f570e6c8cd.jpg)

**Comment by cbeuw** [comment]
Oopsie I didn't consider the slash in filenames

I'll be back home next week and I'll do a patch on this

**Comment by malikshi** [comment]
Please fix it sir :), for time being I'm generate UID until the UID without `/`

**Comment by malikshi** [comment]
@cbeuw does it already fixed?
