### ISSUE TITLE
Installer script

### ISSUE THREAD

**Issue by HirbodBehnam** [cbeuw/Cloak#48]
Hello
Just like before I wrote a _new_ script to install Cloak 2. But not only with shadowsocks, but with anything you like. You can set custom forwarding rules.
Plus with the new Admin Panel API, adding users is completely done by script. You just have to define the quota and ... in script and the script takes care of adding it.

Here is the project link:
https://github.com/HirbodBehnam/Shadowsocks-Cloak-Installer
And here is the installer link:
https://github.com/HirbodBehnam/Shadowsocks-Cloak-Installer/blob/master/Cloak2-Installer.sh

If you like you can put it in readme just like the one in Cloak 1. 

Also I may add built-in openvpn installer later.

**Comment by cbeuw** [comment]
You are a star! Thanks a lot for this!

**Comment by HirbodBehnam** [comment]
Yw
