### ISSUE TITLE
2.0.1 broke https web server fallback

### ISSUE THREAD

**Issue by notsure2** [cbeuw/Cloak#49]
Hello,
The just released 2.0.1 version fails to communicate with fallback https server, nginx reports: 

2019/08/14 10:01:42 [crit] 1118#1118: *19087 SSL_do_handshake() failed (SSL: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:10443

nginx config:
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;

2.0 was working fine.

**Comment by cbeuw** [comment]
Fixed https://github.com/cbeuw/Cloak/releases/tag/v2.0.2

I'll dedicate more time writing more tests, I promise...

**Comment by notsure2** [comment]
Fixed by 2.0.2
