### ISSUE TITLE
What OS are u using? 

### ISSUE THREAD

**Issue by LiveChief** [cbeuw/Cloak#5]
What distro are u using to test it out?

Running this in ubuntu and it's not working anymore , not sure if it's the OS or what but I am assuming it's the OS

Also can u please take a look at this...
The connment...

https://gist.github.com/cbeuw/dd34bf577db85d857ae2f8bb960733e3

**Comment by cbeuw** [comment]
I use ubuntu running on a RPi as my server, and ubuntu running on Windows Subsystem for Linux for development and client testing. The latest version is working fine for me.

How does the log looks like? If you are using the client as a plugin on shadowsocks-windows, you won't be able to see the logs, so in this case please use the standalone mode (same arguments as the standalone mode of GoQuiet) and see the logs

**Comment by LiveChief** [comment]
Its dosent work as intended
