### ISSUE TITLE
json: cannot unmarshal string into Go struct field rawConfig.ProxyBook of type []string

### ISSUE THREAD

**Issue by hvonw** [cbeuw/Cloak#52]
Hi @cbeuw, after upgrading my server and my build env. this issue came up. I do not know the reason is recent commits or a golang related bug?

Thank you for all of your efforts.

`./ck-server -c server.json -p 443 -s 0.0.0.0 
`
```
INFO[0000] Starting standalone mode, listening on 0.0.0.0:443 
FATA[0000] Configuration file error: Failed to read configuration file: json: cannot unmarshal string into Go struct field rawConfig.ProxyBook of type []string
```

Server configuration file:

```
{
"ProxyBook":{
"shadowsocks": "",
"openvpn": "",
"tor": ""},

"BypassUID": "",
"RedirAddr": "",
"PrivateKey": "",
"AdminUID": "",
"DatabasePath": "userinfo.db"
}
```

Build environment:
go1.12.9.linux-amd64 on Ubuntu.

**Comment by cbeuw** [comment]
It's because of the experimental UDP support I just added. I just updated the example config file. This is how it looks like now: https://github.com/cbeuw/Cloak/blob/master/example_config/ckserver.json

**Comment by hvonw** [comment]
Thanks!
Godspeed.
