### ISSUE TITLE
How to change BindAddr in ckserver.json?

### ISSUE THREAD

**Issue by Furthermorer** [cbeuw/Cloak#58]
previous config is 
```
{
  "ProxyBook": {
    "shadowsocks": "127.0.0.1:8388",
  },
  "BypassUID": [
    "1rmq6Ag1jZJCImLBIL5wzQ=="
  ],
  "RedirAddr": "204.79.197.200:443",
  "PrivateKey": "EN5aPEpNBO+vw+BtFQY2OnK9bQU7rvEj5qmnmgwEtUc=",
  "AdminUID": "5nneblJy6lniPJfr81LuYQ==",
  "DatabasePath": "userinfo.db"
}
```
It works, but it uses default port 443, I want to use port 8443.
I changed to this
```
{
  "ProxyBook": {
    "shadowsocks": "127.0.0.1:8388",
  },
  "BypassUID": [
    "1rmq6Ag1jZJCImLBIL5wzQ=="
  ],
  "BindAddr":[":8443"],
  "RedirAddr": "204.79.197.200:443",
  "PrivateKey": "EN5aPEpNBO+vw+BtFQY2OnK9bQU7rvEj5qmnmgwEtUc=",
  "AdminUID": "5nneblJy6lniPJfr81LuYQ==",
  "DatabasePath": "userinfo.db"
}
```
It doesn' work in ip:8443, but works in ip:443(Shadowsocks client)
How to solve this?

**Comment by malikshi** [comment]
2.0.2 still using old config.

**Comment by cbeuw** [comment]
Did you run Cloak as a Shadowsocks plugin? If so, change the port in Shadowsocks' config to 8443

**Comment by Furthermorer** [comment]
> 
> 
> Did you run Cloak as a Shadowsocks plugin? If so, change the port in Shadowsocks' config to 8443

I uses binary release of 2.0.2. 
I changed Shadowsocks-libev's config, changed the port to 8443, but in shadowsocks-client, it still works in ip:443.

config.json
```
{
"server":"0.0.0.0",
"server_port":8443,
"password":"XXXXXX",
"timeout":300,
"user":"nobody",
"method":"xchacha20-ietf-poly1305",
"fast_open":true,
"nameserver":"8.8.8.8",
"mode":"tcp_and_udp"
}

```
ckserver.json
```
{
"ProxyBook":{
"shadowsocks":
"127.0.0.1:8443"
},
"BypassUID":[],
"RedirAddr":"XXXXXX:443",
"PrivateKey":"XXXX",
"AdminUID":"XXXXX",
"DatabasePath":"/etc/cloak/db/userinfo.db"
}

```

**Comment by cbeuw** [comment]
Does it also listen on 8443 as well or only 443?

If you are starting ck-client up from command line you can change its listing port with -p 8443

**Comment by Furthermorer** [comment]
I used the latest binary release 2.1.1，and added "BindAddr":[":8443"] in ckserver.json, problem solved. Thanks.
