### ISSUE TITLE
cloak openvpn udp

### ISSUE THREAD

**Issue by malikshi** [cbeuw/Cloak#60]
`"openvpn": [
      "udp",
      "127.0.0.1:8389"
    ],`
i try that but no luck, no response in server and client
windows client it seem not bind to 127.0.0.1:1984 protocol udp, but when im changing to

`"openvpn": [
      "tcp",
      "127.0.0.1:8989"
    ],`
its working.
maybe you should bind 127.0.0.1:1984 udp/tcp based on client config

>{
  "Transport": "direct",
  "ProxyMethod": "openvpn",
  "ProtocolMethod": "tcp/udp"(choose one)
  "EncryptionMethod": "chacha20-poly1305",
  "UID": "5nneblJy6lniPJfr81LuYQ==",
  "PublicKey": "IYoUzkle/T/kriE+Ufdm7AHQtIeGnBWbhhlTbmDpUUI=",
  "ServerName": "www.bing.com",
  "NumConn": 4,
  "BrowserSig": "chrome",
  "StreamTimeout": 300
}

**Comment by cbeuw** [comment]
On the client side you need to use -u command line argument to let it bind to UDP

**Comment by malikshi** [comment]
thanks work now,
