### ISSUE TITLE
error server stopped working

### ISSUE THREAD

**Issue by malikshi** [cbeuw/Cloak#61]
Sep 22 09:26:39 vultr.guest ck-server[858]: github.com/cbeuw/Cloak/internal/multiplex.(*switchboard).send(0xc00216ab00, 0xc001189000, 0x1c7, 0x4268, 0xc00130
Sep 22 09:26:39 vultr.guest ck-server[858]:         C:/Users/cbeuw/Documents/Go/src/github.com/cbeuw/Cloak/internal/multiplex/switchboard.go:75 +0xf3
Sep 22 09:26:39 vultr.guest ck-server[858]: github.com/cbeuw/Cloak/internal/multiplex.(*Stream).Close(0xc00130c380, 0x0, 0x0)
Sep 22 09:26:39 vultr.guest ck-server[858]:         C:/Users/cbeuw/Documents/Go/src/github.com/cbeuw/Cloak/internal/multiplex/stream.go:158 +0x289
Sep 22 09:26:39 vultr.guest ck-server[858]: github.com/cbeuw/Cloak/internal/util.Pipe(0x9585a0, 0xc00130c380, 0x9587e0, 0xc0021fc040, 0x45d964b800)
Sep 22 09:26:39 vultr.guest ck-server[858]:         C:/Users/cbeuw/Documents/Go/src/github.com/cbeuw/Cloak/internal/util/util.go:105 +0x176
Sep 22 09:26:39 vultr.guest ck-server[858]: created by main.dispatchConnection
Sep 22 09:26:39 vultr.guest ck-server[858]:         C:/Users/cbeuw/Documents/Go/src/github.com/cbeuw/Cloak/cmd/ck-server/ck-server.go:183 +0x198b
Sep 22 09:26:39 vultr.guest systemd[1]: cloak-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by malikshi** [comment]
oke fix, i just try build cloak,

**Comment by klaaktu** [comment]
Does this issue affect v2.1.1 release in the release page? Or is it a build issue?

**Comment by malikshi** [comment]
Its 2.1.1 error like that. You must build cloak yourself to get fixed binary.
