### ISSUE TITLE
About "server name"

### ISSUE THREAD

**Issue by windstander** [cbeuw/Cloak#67]
In the readme, "RedirAddr is the redirection address when the incoming traffic is not from a Cloak client. It should either be the same as, or correspond to the IP record of the ServerName field set in ckclient.json"

but after installation with that script, it says server name can "use anything you want", while the redirect IP is one of bing.com by default.

I tried to set the redirect IP to another site and set the server name to the domain of that site, but the cloak plugin dosen't work properly.

**Comment by cbeuw** [comment]
Does it give any log outputs?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by windstander** [comment]
Where to find the log?

**Comment by HirbodBehnam** [comment]
With my script try `systemctl status cloak-server`

**Comment by windstander** [comment]
Readme says the redirect IP must belong to the "server name", while after installation the script says the server name can be any site you want.

**Comment by HirbodBehnam** [comment]
I will change the script

**Comment by windstander** [comment]
Thank you for your script.

I am busy and cannot get the log.

I set the redirect IP to 104.85.216.15 and set the server name to steampowered.com. But the SS and cloak do not work. You can try it.

I want to masquerade as visiting the Steam site.

**Comment by cbeuw** [comment]
If Cloak is already working with default settings, changing `ServerName` should have no bearing on the connection as it's just there for the firewall to see. Cloak server doesn't do anything with it

**Comment by windstander** [comment]
> 
> 
> If Cloak is already working with default settings, changing `ServerName` should have no bearing on the connection as it's just there for the firewall to see. Cloak server doesn't do anything with it

This time it works. You mean redirect IP can be any site's IP and the user can set any site's domain as server name?

**Comment by windstander** [comment]
> 
> 
> With my script try `systemctl status cloak-server`

Failed again

Sep 27 17:08:50 instance-1 systemd[1]: Started Cloak Server Service.
Sep 27 17:08:50 instance-1 systemd[644]: cloak-server.service: Failed at step EXEC spawning /usr/local/bin/ck-serve
Sep 27 17:08:50 instance-1 systemd[1]: cloak-server.service: Main process exited, code=exited, status=203/EXEC
Sep 27 17:08:50 instance-1 systemd[1]: cloak-server.service: Unit entered failed state.
Sep 27 17:08:50 instance-1 systemd[1]: cloak-server.service: Failed with result 'exit-code'.
lines 1-10/10 (END)

**Comment by windstander** [comment]
rebooted

cloak-server.service - Cloak Server Service
   Loaded: loaded (/etc/systemd/system/cloak-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-09-27 17:16:55 CST; 5min ago
  Process: 660 ExecStart=/usr/local/bin/ck-server -c ckserver.json (code=exited, status=1/FAILURE)
 Main PID: 660 (code=exited, status=1/FAILURE)

Sep 27 17:16:55 instance-1 systemd[1]: Started Cloak Server Service.
Sep 27 17:16:55 instance-1 ck-server[660]: 2019/09/27 17:16:55 ck-server.go:244: Must specify localAddr
Sep 27 17:16:55 instance-1 systemd[1]: cloak-server.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 17:16:55 instance-1 systemd[1]: cloak-server.service: Unit entered failed state.
Sep 27 17:16:55 instance-1 systemd[1]: cloak-server.service: Failed with result 'exit-code'.

**Comment by windstander** [comment]
cloak-server.service - Cloak Server Service
   Loaded: loaded (/etc/systemd/system/cloak-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-09-27 17:33:04 CST; 6min ago
 Main PID: 650 (code=exited, status=203/EXEC)

Sep 27 17:33:04 instance-1 systemd[1]: Started Cloak Server Service.
Sep 27 17:33:04 instance-1 systemd[1]: cloak-server.service: Main process exited, code=exited, status=203/EXEC
Sep 27 17:33:04 instance-1 systemd[1]: cloak-server.service: Unit entered failed state.
Sep 27 17:33:04 instance-1 systemd[1]: cloak-server.service: Failed with result 'exit-code'.

**Comment by windstander** [comment]
> 
> 
> I will change the script
> Sry for this

You are adjusting the script? Everytime I reinstall the plugin, the steps are changed.

**Comment by HirbodBehnam** [comment]
Can you manually run
`ck-server -c /etc/cloak/ckserver.json`
and can you post `/etc/cloak/ckserver.json` file?

**Comment by windstander** [comment]
I uninstalled the plugin and wait for the new script.

Thank you all.

**Comment by HirbodBehnam** [comment]
The script is fine on my server. I still have no idea what is causing the problem for you

**Comment by windstander** [comment]
> 
> 
> Can you manually run
> `ck-server -c /etc/cloak/ckserver.json`
> and can you post `/etc/cloak/ckserver.json` file?
> 
> Edit:
> What do you mean about steps are changed? And no I'm not editing the script

root@instance-1:/home/XXX# ck-server -c /etc/cloak/ckserver.json
2019/09/27 19:53:02 ck-server.go:244: Must specify localAddr

**Comment by malikshi** [comment]
@windstander did you use script install cloak from @HirbodBehnam ? its should be working

**Comment by windstander** [comment]
> 
> 
> @windstander did you use script install cloak from @HirbodBehnam ? its should be working

I use it on GCP.

**Comment by windstander** [comment]
> 
> 
> Can you manually run
> `ck-server -c /etc/cloak/ckserver.json`
> and can you post `/etc/cloak/ckserver.json` file?
> 
> Edit:
> What do you mean about steps are changed? And no I'm not editing the script

Before, it will ask me whether create my own net rule, but now it does not ask me and directly show the QRcode of the shadowsocks.

**Comment by windstander** [comment]
> 
> 
> Can you manually run
> `ck-server -c /etc/cloak/ckserver.json`
> and can you post `/etc/cloak/ckserver.json` file?
> 
> Edit:
> What do you mean about steps are changed? And no I'm not editing the script

And now the default server name is the redirect IP, not bing.com

**Comment by HirbodBehnam** [comment]
I still asks you if you want to set custom rules. After asking which dns server you want to use

**Comment by windstander** [comment]
Now it works fine.

> 
> 
> I still asks you if you want to set custom rules. After asking which dns server you want to use
