### ISSUE TITLE
能不能请教一下，路由器上怎么配置客户端呀

### ISSUE THREAD

**Issue by qwerttvv** [cbeuw/Cloak#80]
现在服务端和win还有手机都照猫画虎的调通了，想在路由器上弄好……不知道怎么弄了

路由一个k3，先后折腾了好几个固件，无果

还有一个路由是新3，目前刷hiboy的老毛子，主力路由，ss插件好像支持GoQuite，GoQuite的话没有试，直接弄的Cloak，但是死活弄不好。。。

**Comment by ntgeralt** [comment]
行。批准你10天假吧

**Comment by qwerttvv** [comment]
额。。。。请教。。。。。

**Comment by qwerttvv** [comment]
直接运行就是standalone mode模式的，ss不能调用，没办法Plugin mode

**Comment by ntgeralt** [comment]
你啃10篇全英文操作帖子应该就懂了，好像还要json挂载

**Comment by qwerttvv** [comment]
> 你啃10篇全英文操作帖子应该就懂了，好像还要json挂载

emmmmm,搞到现在已经脑袋大咯，实在不会弄：（

**Comment by zhiming-xu** [comment]
@qwerttvv I have replied to you in [another issue](https://github.com/cbeuw/Cloak/issues/56#issuecomment-566851573), please see if this could help.
