### ISSUE TITLE
there is a bug or something?

### ISSUE THREAD

**Issue by qwerttvv** [cbeuw/Cloak#90]
browse https://archive.is & https://archive.today with cloak

click advanced

click go on

did you see what happened?

if you ServerName is ip, that is your ServerName website in your client config……

if you ServerName is hostname, it will show some error info like:

```
Invalid URL
The requested URL "[no URL]", is invalid.
Reference #9.36fb3f17.1579069981.322940d5
```

**Comment by klaaktu** [comment]
ck-server says this when I visit the site:
```
level=warning msg="transport TLS in correct format but not Cloak: cipher: message authentication failed" UID= encryptionMethod=0 proxyMethod= remoteAddr="127.0.0.1:33258"
```

**Comment by qwerttvv** [comment]
> ck-server says this when I visit the site:
> 
> ```
> level=warning msg="transport TLS in correct format but not Cloak: cipher: message authentication failed" UID= encryptionMethod=0 proxyMethod= remoteAddr="127.0.0.1:33258"
> ```

same msg

**Comment by cbeuw** [comment]
Where is the "advanced" button in the website? I couldn't find it..

**Comment by klaaktu** [comment]
It's the browser security warning thing I think? e.g. in Chrome click "advanced" in the warning page to reveal "proceed to unsafe website" option.

**Comment by cbeuw** [comment]
@klaaktu Hmmm it doesn't happen to me. I think there's DNS poisoning on that domain

**Comment by cbeuw** [comment]
Actually this is a very interesting behaviour. Try `ping archive.is` and see what IP you got. It's 46.45.185.48 for me

**Comment by klaaktu** [comment]
At first I thought the website just redirects any potential spam address back to themselves...
archive.is
On VPS: 62.192.168.106
DNSCrypt on PC: 217.79.184.91
archive.ph
On VPS: 62.192.168.106
DNSCrypt on PC: 69.63.184.30

**Comment by qwerttvv** [comment]
you can try with https://tools.ipip.net/ping.php

there is lots of server in the world

**Comment by klaaktu** [comment]
Nvm, I was using CloudFlare DNS for Shadowsocks.
[Dig @1.1.1.1 archive.is returns 127.0.0.5](https://en.wikipedia.org/wiki/Archive.today#Worldwide) which is loopback address...

**Comment by qwerttvv** [comment]
i see....

now, i set ss to use 8.8.8.8.......
